# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: shiny-deploy

on:
  pull_request:
    branches:
      - staging
  push:
    branches:
      - main
      - staging


jobs:
  shiny-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
      SYNAPSE_AUTH_TOKEN: ${{ secrets.SYNAPSE_AUTH_TOKEN }}
    steps:
      - name: Install libcurl
        run: sudo apt-get install -y libcurl4-openssl-dev

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2

      - name: Install Miniconda and python packages
        run: |
          reticulate::install_miniconda()
          reticulate::py_discover_config()
          reticulate::py_install(c('pandas', 'numpy', 'boto3', 'synapseclient'), pip = TRUE)
        shell: Rscript {0}

      - name: Authorize and deploy app
        run: |
          yaml::write_yaml(
            list("access_token" = ${{ secrets.SYNAPSE_AUTH_TOKEN }}),
            "app_config.yml"
          )
          branch <- Sys.getenv("GITHUB_REF_NAME")
          if (branch == "main"){
            app_name <- "Shiny-Module-Gallery"
          } else if (branch == "staging"){
            app_name <- "Shiny-Module-Gallery-staging"
          } else {
            app_name <- "Shiny-Module-Gallery-testing"
          }
          print(app_name)
          rsconnect::setAccountInfo(
            name   = "sagebio",
            token  = "${{ secrets.RSCONNECT_TOKEN }}",
            secret = "${{ secrets.RSCONNECT_SECRET }}"
          )
          rsconnect::deployApp(appName = app_name)

        shell: Rscript {0}


